### ISSUE TITLE
Error calling Home Assistant service

### ISSUE THREAD

**Issue by barcik75** [NiklasReiche/ad-spotify-mood-lights-sync#12]
Hi,
I have problem. I installed everything and when I started music on my spotify device in AppDemon logs I got this:
```
2023-02-23 21:06:45.778775 WARNING HASS: Error calling Home Assistant service default/homeassistant/turn_on
2023-02-23 21:06:45.779657 WARNING HASS: Code: 500, error: 500 Internal Server Error
Server got itself in trouble
```
I don't know if I missed something or if I need to configure something else. I added spotips to the AppDeamon settings, in the app.yaml file I added the basic configuration. I changed my login details to mine for Spotify. In the AppDeamon interface I can see this app. I don't see anything disturbing in the logs in the interface either.
After every new song, there is a new entry with the same error.

**Comment by NiklasReiche** [comment]
It seems like your Spotify configuration is correct, given that there are no other errors. But apparently there's a problem when calling the `turn_on` service on your light entity. I see two potential error sources: either the light entity doesn't exist/isn't available, or it doesn't support the attributes that the app uses for the `turn_on` service for some reason (the app sets the color through the `rgb_color` attribute, but it wouldn't be difficult to add an option to use `hs_color` instead).

To narrow the problem down please do the following:
- Double-check that the entity you put in the `light` option on the app config exists in your Home Assistant and is reachable from Home Assistant
- If the light entity in the config is correct, could you share what kind of light you are using (brand/model of your light bulb and/or integration used)? Also, is it a single light or a group of entities you are using?

**Comment by barcik75** [comment]
Thank you for your response. 
Sorry for the confusion, Turns out I made a typo in the entity name, that's why it didn't work. Now everything is fine.
Thanks again for the nice addition and your work.
